modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL=""
showAsResourcePack=false

[[mods]]
modId="mcmodshow"
version="${file.jarVersion}"
displayName="MC Mod Show Background"
description='''
Replaces the Minecraft main menu background with a customizable image that is automatically normalized for you.
'''

[[dependencies.mcmodshow]]
modId="forge"
mandatory=true
versionRange="[47.2.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.mcmodshow]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="CLIENT"
